### ISSUE TITLE
Pretrained model is wrong

### ISSUE THREAD

**Issue by Cogito2012** [ai4ce/EgoPAT3D#5]
Hi,

Thank you for sharing this great work! When I was trying to run the `test.py` with your provided pre-trained model file `LSTM.pth`, the program reported the mismatch errors between the checkpoint file and the LSTM-based model. 

Seems that the pretrained model `LSTM.pth` is actually a **GRU-based** model. I appreciate your time to double-check with it. 

Thank you!

**Comment by ziangcao0312** [comment]
Thanks for your attention. We have updated the code. Please use the latest version. If the problem is solved, please close this issue.

**Comment by Cogito2012** [comment]
Thank you for the timely response! 
The updated code could match with the pre-trained model now. I'll close this issue.
