### ISSUE TITLE
How to obtain the aligned depth from raw MKV videos?

### ISSUE THREAD

**Issue by Cogito2012** [ai4ce/EgoPAT3D#6]
Hi,

Thanks for releasing this great dataset!

I'm interested in the RGB-aligned depth frames, as shown in your paper's 3rd column of figure 3. However, I found it is really challenging to them from your provided raw MKV videos.

I noticed that you kindly provided the preprocessing code [here](https://github.com/ai4ce/EgoPAT3D/blob/a9d874df74e5e0157dab26b0b5e6f1ae6ee1f26e/preprocessing/mkv2d2rgbrgb.py#L52). But the `pyk4a` package used here relies on the installation of Azure Kinect SDK which only supports Windows and Ubuntu 18.04 on a **non-headless** machine (with a monitor connected to enable the OpenGL).  However, I only have macOS laptop and headless remote Ubuntu server. Could you tell what are your software and hardware environment when running the preprocessing code?

Currently, I only have the luck to extract the raw depth (the 2nd column of figure 3 in your paper) by using the `Open3D` mkv video reader on a headless server. Therefore, I was also wondering if there is any other way to transform the raw depth into the RGB camera.

I believe it would further strengthen the EgoPAT3D dataset if the aligned depth could be released. Looking forward to hearing from your suggestions. Thank you!

**Comment by simbaforrest** [comment]
@Cogito2012 Thank you for the suggestion and the interest in the dataset! If you are coming to CVPR'22 in person, you should definitely come to our poster and chat with us.

Regarding the data alignment, I am directing the question to @ziangcao0312 and @RoboticsYimingLi as well as @aliang322 to help answer it.

**Comment by Cogito2012** [comment]
Hi Dr. Feng,

Thanks! I’ll come to CVPR’22 in person. Looking forward to discussing with
you there!

Best,
Wentao

**Comment by simbaforrest** [comment]
>

**Comment by simbaforrest** [comment]
Hi @Cogito2012 , it was nice meeting you in person at CVPR'22. Is your problem addressed? If not, feel free to reopen it until we address it. 

You are very welcome to provide further suggestions!

**Comment by Cogito2012** [comment]
> Hi @Cogito2012 , it was nice meeting you in person at CVPR'22. Is your problem addressed? If not, feel free to reopen it until we address it.
> 
> You are very welcome to provide further suggestions!

Hi @simbaforrest nice to meet with you at CVPR'22! I chatted with Yiming at the poster session, and got some useful advices. Eventually, I found a Windows workstation with monitor connected, and now the aligned depth can be obtained by `pyk4a` package. Thank you for taking care of my issue!
